name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  tox:
    name: tox (${{ matrix.project.repository }})
    uses: vexxhost/docker-atmosphere/.github/workflows/tox.yml@5923a8fba3a98cf17e36583cc498d5e70a01c482 # main
    strategy:
      fail-fast: false
      matrix:
        project:
          - repository: openstack/ovn-bgp-agent
            ref: 8c86978a1a2043dab38eaa7566aacecb9025c427 # master
    with:
      repository: ${{ matrix.project.repository }}
      ref: ${{ matrix.project.ref }}

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          repository: openstack/ovn-bgp-agent
          ref: 8c86978a1a2043dab38eaa7566aacecb9025c427 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          image-name: ovn-bgp-agent
          build-contexts: ovn-bgp-agent=openstack/ovn-bgp-agent
          push: ${{ github.event_name != 'pull_request' }}
